apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spock-grafana
spec:
  serviceName: spock-grafana-svc
  replicas: 1
  selector:
    matchLabels:
      app: spock-grafana
  volumeClaimTemplates:
  - metadata:
      name: grafana-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
  template:
    metadata:
      labels:
        app: spock-grafana
    spec:
      containers:
        - name: spock-grafana
          image: grafana/grafana
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 600m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 128Mi
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
