apiVersion: v1
kind: Service
metadata:
  name: spock-grafana-svc
  namespace: default
  labels:
     app: spock-grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: spock-grafana
